-- Insert a new customer, market, date, products-- 
INSERT INTO customers(customer_code,custmer_name,customer_type) 
VALUES('Cus039','Mohit Kumar','Brick & Mortar');

-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Know your market zones, customer types and product types --
SELECT DISTINCT zone FROM markets;
SELECT DISTINCT customer_type FROM customers;
SELECT DISTINCT product_type FROM products;
SELECT DISTINCT currency FROM transactions;

-- Know how many transactions are there ? --
SELECT COUNT(*) FROM transactions;

-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- LEARNING FACE --
SELECT COUNT(*) FROM transactions WHERE market_code = 'Mark001';  -- TOTAL TRANSACTIONS DONE IN CHENNAI (MARKET CODE 001)
SELECT SUM(sales_amount) FROM transactions WHERE market_code = 'Mark001';  -- TOTAL AMOUNT GENEREATED FROM CHENNAI (MARKET CODE 001)

-- SYNTAX --> SELECT table_name1.*, tabele_name2.column_name FROM table_name1 INNER JOIN table_name2 ON (condition like = )
SELECT transactions.*, date.year FROM transactions INNER JOIN 
date ON transactions.order_date=date.date;

SELECT transactions.*, date.year FROM transactions INNER JOIN 
date ON transactions.order_date=date.date WHERE year=2017;

SELECT COUNT(*) FROM transactions INNER JOIN 
date ON transactions.order_date=date.date WHERE year=2017;

SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN 
date ON transactions.order_date=date.date WHERE year=2020 AND month_name='January';

-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SALES INSIGHTS ANALYSIS -- 
SELECT SUM(transactions.sales_amount) FROM transactions; -- TOTAL AMOUNT GENERATED FROM OVERALL BUSSINESS
SELECT SUM(transactions.sales_qty) FROM transactions; -- TOTAL PRODUCT SOLD FROM OVERALL BUSSINESS

-- 1. REVENUE BY MARKET 
-- 1.a. OVERALL MARKET SALES AMOUNT GENERATED
SELECT SUM(transactions.sales_amount) FROM transactions WHERE market_code='MARK001'; 
SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN markets ON transactions.market_code = markets.markets_code 
WHERE market_code='MARK001'; -- Overall amount generated in chennai 

-- 1.b. MARKET SALES AMOUNT GENERATED BY YEAR OR MONTH 
SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2017 AND market_code='MARK001';  -- amount generated in 2017 in chennai

SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2018 AND month_name='November' AND market_code='MARK001'; -- amount generated in november,2018 in chennai

-- 2. SALES QUANTITY BY MARKET
-- 2.a OVERALL PRODUCT SOLD
SELECT SUM(transactions.sales_qty) FROM transactions WHERE market_code='MARK001'; 
SELECT SUM(transactions.sales_qty) FROM transactions INNER JOIN products ON transactions.product_code = products.product_code 
WHERE market_code='MARK001'; -- Overall product sold in chennai

-- 2.b OVERALL PRODUCT SOLD IN PARTICULAR YEAR OR MONTH
SELECT SUM(transactions.sales_qty) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2017 AND market_code='MARK001';  -- product sold in 2017 in chennai

SELECT SUM(transactions.sales_qty) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2018 AND month_name='November' AND market_code='MARK001'; -- product sold in november,2018 in chennai

-- 3. TOP 5 PRODUCTS 
SELECT product_code, COUNT(sales_amount), SUM(sales_amount) FROM transactions GROUP BY product_code 
ORDER BY COUNT(sales_amount) DESC LIMIT 5; -- TOP 5 SELLING PRODUCTS

SELECT product_code, SUM(sales_amount) FROM transactions GROUP BY product_code 
ORDER BY SUM(sales_amount) DESC limit 5 ; -- Total amount generated by those top 5 selling products 

-- 4. TOP 5 CUSTOMERS 
SELECT transactions.customer_code, customers.custmer_name, SUM(transactions.sales_amount) FROM transactions 
INNER JOIN customers ON transactions.customer_code=customers.customer_code GROUP BY customer_code
ORDER BY SUM(transactions.sales_amount) DESC LIMIT 5; -- TOP 5 CUSTOMERS

-- 5. YEARLY SALES
SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2017 AND market_code='MARK001';  -- amount generated in 2017 in chennai

-- 6. MONTHLY SALES
SELECT SUM(transactions.sales_amount) FROM transactions INNER JOIN date ON transactions.order_date = date.date 
WHERE year=2018 AND month_name='November' AND market_code='MARK001'; -- amount generated in november,2018 in chennai










